### ISSUE TITLE
Possible to have a fixed height?

### ISSUE THREAD

**Issue by Rainer-Lang** [roughike/SwipeSelector#11]
As seen in the sample app, the height changes. Is it possible that the height is from the beginning the max needed height?

**Comment by roughike** [comment]
Yeah, it is possible.

I think this is more of a taste issue. To me, there's no reason to take all the extra space if the currently showing item doesn't need it. While someone else might prefer it the same way as you do.

I'll add an option to have it fixed size all the time.

**Comment by Rainer-Lang** [comment]
@roughike It's a thing about UX. If something "jumps" or "changes" the user's focus will be interrupted and he will start searching where the change appeared....
Anyway, thank you for adding this option. :+1:

**Comment by roughike** [comment]
@Rainer-Lang 
I get where you're coming from. When the descriptions are short, the jumping is annoying. But when the some descriptions are really long and some are not, the shorter ones just look like they're taking a lot of unnecessary space.

That's why the default behavior is the way it is, to handle even a novel without the more empty views taking space. But I'm making it an option so everyone can be happy.

I knew this was going to be talked about at some point when not including it... ;D

**Comment by Rainer-Lang** [comment]
@roughike I completely understand why the default behavior is what it is. :)
If the dev uses a fixed height and all looks ugly it's his turn... ;-)
